historical_steps: 20
future_steps: 30
num_modes: 6
rotate: true
node_dim: 2
edge_dim: 2
embed_dim: 64
num_heads: 8
dropout: 0.1
num_temporal_layers: 4
num_global_layers: 3
local_radius: 50
parallel: false
lr: 0.0005
weight_decay: 0.0001
T_max: 64
root: /
train_batch_size: 32
val_batch_size: 32
shuffle: true
num_workers: 8
pin_memory: true
persistent_workers: true
gpus: 1
max_epochs: 64
monitor: val_minFDE
save_top_k: 5
