historical_steps: 50
future_steps: 60
num_modes: 6
rotate: true
node_dim: 2
edge_dim: 2
dim: 128
num_heads: 8
dropout: 0.1
num_temporal_layers: 4
num_global_layers: 3
local_radius: 50
parallel: false
reduce_his_length: false
random_his_length: false
random_interpolate_zeros: false
valid_observation_length: 20
lr: 5e-4
weight_decay: 1e-4
T_max: 64
embed_dim: 128