_target_: src.datamodule.av1_datamodule.Av1DataModule

data_root: ${data_root}
data_folder: ${model.name}
train_batch_size: ${batch_size}
val_batch_size: ${batch_size}
test_batch_size: ${batch_size}
shuffle: True
num_workers: ${num_workers}
pin_memory: True
pyg: false
test: false
collate_fn: ${model.collate_fn}
expand_trainval: ${expand_trainval}